bootstrap.servers=broker:29092
group.id=kc-hot-product-demo

config.storage.topic=connect-configs-hot-product-demo
offset.storage.topic=connect-offsets-hot-product-demo
status.storage.topic=connect-status-hot-product-demo

config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
header.converter=org.apache.kafka.connect.storage.SimpleHeaderConverter

plugin.path=/usr/share/confluent-hub-components,/usr/share/java,/opt/connect-plugins

rest.host.name=0.0.0.0
rest.advertised.host.name=connect
rest.port=8083

offset.flush.interval.ms=10000
